name: Run Go
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18.1"
        env:
          NEW_MONEY: ${{ secrets.NEW_MONEY }}       
      - run: go run main.go
